export const ABI_TRANSCRIPTIONS = [
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'bytes32', name: 'request_id', type: 'bytes32' },
      { indexed: false, internalType: 'uint256', name: 'created_at', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'last_updated_at', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'creator', type: 'address' },
      { indexed: false, internalType: 'bool', name: 'receiving_transcripts', type: 'bool' },
      { indexed: false, internalType: 'bool', name: 'fulfilled', type: 'bool' },
      { indexed: false, internalType: 'string', name: 'metadata_uri', type: 'string' },
      { indexed: false, internalType: 'address[]', name: 'collaborators', type: 'address[]' },
    ],
    name: 'requestCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'bytes32', name: 'request_id', type: 'bytes32' }],
    name: 'requestDeleted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'bytes32', name: 'request_id', type: 'bytes32' },
      { indexed: false, internalType: 'bool', name: 'receiving_transcripts', type: 'bool' },
      { indexed: false, internalType: 'bool', name: 'fulfilled', type: 'bool' },
    ],
    name: 'requestStateUpdate',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'bytes32', name: 'id_revision', type: 'bytes32' },
      { indexed: false, internalType: 'bytes32', name: 'transcript_id', type: 'bytes32' },
      { indexed: false, internalType: 'address', name: 'creator', type: 'address' },
      { indexed: false, internalType: 'string', name: 'content_uri', type: 'string' },
      { indexed: false, internalType: 'enum Grimoire.revisionStates', name: 'state', type: 'uint8' },
    ],
    name: 'revisionCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'bytes32', name: 'id_revision', type: 'bytes32' },
      { indexed: false, internalType: 'bytes32', name: 'id_transcript', type: 'bytes32' },
      { indexed: false, internalType: 'enum Grimoire.revisionStates', name: 'state', type: 'uint8' },
    ],
    name: 'revisionStateChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'bytes32', name: 'request_id', type: 'bytes32' },
      { indexed: false, internalType: 'bytes32', name: 'transcript_id', type: 'bytes32' },
      { indexed: false, internalType: 'address', name: 'collaborator', type: 'address' },
    ],
    name: 'transcriptApproved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'bytes32', name: 'transcript_id', type: 'bytes32' },
      { indexed: false, internalType: 'uint256', name: 'created_at', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'last_updated_at', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'creator', type: 'address' },
      { indexed: false, internalType: 'address[]', name: 'contributors', type: 'address[]' },
      { indexed: false, internalType: 'string[]', name: 'revision_metadata_uris', type: 'string[]' },
      { indexed: false, internalType: 'string', name: 'metadata_uri', type: 'string' },
      { indexed: false, internalType: 'bytes32', name: 'id_request', type: 'bytes32' },
      { indexed: false, internalType: 'string[]', name: 'communities', type: 'string[]' },
    ],
    name: 'transcriptCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'bytes32', name: 'transcript_id', type: 'bytes32' }],
    name: 'transcriptDeleted',
    type: 'event',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'revision_id', type: 'bytes32' }],
    name: 'acceptRevision',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'address_to_request',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'address_to_revision',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'address_to_transcripts',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'transcript_id', type: 'bytes32' },
      { internalType: 'bytes32', name: 'request_id', type: 'bytes32' },
    ],
    name: 'approveTranscript',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'created_at', type: 'uint256' },
      { internalType: 'string', name: 'metadata_uri', type: 'string' },
      { internalType: 'address[]', name: 'collaborators', type: 'address[]' },
    ],
    name: 'createRequest',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'created_at', type: 'uint256' },
      { internalType: 'address[]', name: 'contributors', type: 'address[]' },
      { internalType: 'string', name: 'metadata_uri', type: 'string' },
      { internalType: 'bytes32', name: 'id_request', type: 'bytes32' },
      { internalType: 'string[]', name: 'communities', type: 'string[]' },
    ],
    name: 'createTranscription',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'request_id', type: 'bytes32' }],
    name: 'deleteRequest',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'transcription_id', type: 'bytes32' }],
    name: 'deleteTranscription',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'request_id', type: 'bytes32' }],
    name: 'getProposalsByRequestId',
    outputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'transcription_id', type: 'bytes32' },
          { internalType: 'uint256', name: 'created_at', type: 'uint256' },
          { internalType: 'uint256', name: 'last_updated_at', type: 'uint256' },
          { internalType: 'address', name: 'creator', type: 'address' },
          { internalType: 'address[]', name: 'contributors', type: 'address[]' },
          { internalType: 'string[]', name: 'revision_metadata_uris', type: 'string[]' },
          { internalType: 'string', name: 'metadata_uri', type: 'string' },
          { internalType: 'bytes32', name: 'id_request', type: 'bytes32' },
          { internalType: 'string[]', name: 'communities', type: 'string[]' },
          { internalType: 'bool', name: 'exists', type: 'bool' },
        ],
        internalType: 'struct Grimoire.Transcription[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'request_id', type: 'bytes32' }],
    name: 'getRequest',
    outputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'request_id', type: 'bytes32' },
          { internalType: 'uint256', name: 'created_at', type: 'uint256' },
          { internalType: 'uint256', name: 'last_updated_at', type: 'uint256' },
          { internalType: 'address', name: 'creator', type: 'address' },
          { internalType: 'bool', name: 'receiving_transcripts', type: 'bool' },
          { internalType: 'bool', name: 'fullfiled', type: 'bool' },
          { internalType: 'string', name: 'metadata_uri', type: 'string' },
          { internalType: 'address[]', name: 'collaborators', type: 'address[]' },
          { internalType: 'bytes32', name: 'id_linked_transcription', type: 'bytes32' },
          { internalType: 'bool', name: 'exists', type: 'bool' },
        ],
        internalType: 'struct Grimoire.Request',
        name: 'request',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'revision_id', type: 'bytes32' }],
    name: 'getRevision',
    outputs: [
      { internalType: 'string', name: 'content_uri', type: 'string' },
      { internalType: 'uint256', name: 'revision_index', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'transcription_id', type: 'bytes32' },
      { internalType: 'enum Grimoire.revisionStates', name: 'state', type: 'uint8' },
    ],
    name: 'getRevisionsByTranscriptionId',
    outputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'id_revision', type: 'bytes32' },
          { internalType: 'bytes32', name: 'transcript_id', type: 'bytes32' },
          { internalType: 'address', name: 'creator', type: 'address' },
          { internalType: 'string', name: 'content_uri', type: 'string' },
          { internalType: 'enum Grimoire.revisionStates', name: 'state', type: 'uint8' },
          { internalType: 'bool', name: 'exists', type: 'bool' },
        ],
        internalType: 'struct Grimoire.Revision[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'transcript_id', type: 'bytes32' }],
    name: 'getTranscript',
    outputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'transcription_id', type: 'bytes32' },
          { internalType: 'uint256', name: 'created_at', type: 'uint256' },
          { internalType: 'uint256', name: 'last_updated_at', type: 'uint256' },
          { internalType: 'address', name: 'creator', type: 'address' },
          { internalType: 'address[]', name: 'contributors', type: 'address[]' },
          { internalType: 'string[]', name: 'revision_metadata_uris', type: 'string[]' },
          { internalType: 'string', name: 'metadata_uri', type: 'string' },
          { internalType: 'bytes32', name: 'id_request', type: 'bytes32' },
          { internalType: 'string[]', name: 'communities', type: 'string[]' },
          { internalType: 'bool', name: 'exists', type: 'bool' },
        ],
        internalType: 'struct Grimoire.Transcription',
        name: 'request',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'id_to_request',
    outputs: [
      { internalType: 'bytes32', name: 'request_id', type: 'bytes32' },
      { internalType: 'uint256', name: 'created_at', type: 'uint256' },
      { internalType: 'uint256', name: 'last_updated_at', type: 'uint256' },
      { internalType: 'address', name: 'creator', type: 'address' },
      { internalType: 'bool', name: 'receiving_transcripts', type: 'bool' },
      { internalType: 'bool', name: 'fullfiled', type: 'bool' },
      { internalType: 'string', name: 'metadata_uri', type: 'string' },
      { internalType: 'bytes32', name: 'id_linked_transcription', type: 'bytes32' },
      { internalType: 'bool', name: 'exists', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'id_to_revision',
    outputs: [
      { internalType: 'bytes32', name: 'id_revision', type: 'bytes32' },
      { internalType: 'bytes32', name: 'transcript_id', type: 'bytes32' },
      { internalType: 'address', name: 'creator', type: 'address' },
      { internalType: 'string', name: 'content_uri', type: 'string' },
      { internalType: 'enum Grimoire.revisionStates', name: 'state', type: 'uint8' },
      { internalType: 'bool', name: 'exists', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'id_to_transcription',
    outputs: [
      { internalType: 'bytes32', name: 'transcription_id', type: 'bytes32' },
      { internalType: 'uint256', name: 'created_at', type: 'uint256' },
      { internalType: 'uint256', name: 'last_updated_at', type: 'uint256' },
      { internalType: 'address', name: 'creator', type: 'address' },
      { internalType: 'string', name: 'metadata_uri', type: 'string' },
      { internalType: 'bytes32', name: 'id_request', type: 'bytes32' },
      { internalType: 'bool', name: 'exists', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'transcript_id', type: 'bytes32' },
      { internalType: 'uint256', name: 'updated_time', type: 'uint256' },
      { internalType: 'string', name: 'content_uri', type: 'string' },
    ],
    name: 'proposeRevision',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'revision_id', type: 'bytes32' }],
    name: 'rejectRevision',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: '', type: 'bytes32' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'request_id_to_proposals',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: '', type: 'bytes32' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'transcript_id_to_revisions',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'request_id', type: 'bytes32' },
      { internalType: 'bool', name: 'receiving_transcripts', type: 'bool' },
      { internalType: 'bool', name: 'fulfilled', type: 'bool' },
    ],
    name: 'updateRequestStatus',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
]
export const CONTRACT_TRANSCRIPTIONS = {
  // Chiado
  10200: {
    chainId: 10200,
    address: '0x92C410556C7AeD3C9aa6ED3552431C876770FF99',
    abi: ABI_TRANSCRIPTIONS,
  },
  // Mumbai testnet
  80001: {
    chainId: 80001,
    address: '0xD9f939e8eCD876Ca0908E8CE35C109161488E895',
    abi: ABI_TRANSCRIPTIONS,
  },
  // Optimism Goerli
  420: {
    chainId: 420,
    address: '0x239b986D8B3bAB3e89D9586a5D83c5C0B08Fc3D3',
    abi: ABI_TRANSCRIPTIONS,
  },
  // Filecoin Hyperspace
  3141: {
    chainId: 3141,
    address: '0x27B485cD095d4EC7181eE867c991E38654B7F3AA',
    abi: ABI_TRANSCRIPTIONS,
  },
  // Scroll Alpha testnet
  534353: {
    chainId: 534353,
    address: '0xF91F71e2AB73a5298CAb2aD8df0EBE6e176961Ce',
    abi: ABI_TRANSCRIPTIONS,
  },
  // Taiko Sepolia
  11155111: {
    chainId: 11155111,
    address: '0xF91F71e2AB73a5298CAb2aD8df0EBE6e176961Ce',
    abi: ABI_TRANSCRIPTIONS,
  },
  // Polygon zkEVM Testnet
  1442: {
    chainId: 1442,
    address: '0xF91F71e2AB73a5298CAb2aD8df0EBE6e176961Ce',
    abi: ABI_TRANSCRIPTIONS,
  },
}
